### ISSUE TITLE
Webpack Error after after adding plugin

### ISSUE THREAD

**Issue by arjunkomath** [nuxt/webpackbar#1]
I'm unable to run webpack after adding the plugin, stack trace is as below:

Node version: v9.3.0
Webpack version: 3.10.0
Package version: 1.1.3

```
/usr/local/lib/node_modules/webpack/bin/webpack.js:348
			throw err;
			^

TypeError: Cannot read property 'done' of undefined
    at WebpackBarPlugin.apply (/Users/arjun/Projects/dashboard/node_modules/webpackbar/dist/index.js:61:20)
    at Compiler.apply (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/usr/local/lib/node_modules/webpack/lib/webpack.js:33:19)
    at processOptions (/usr/local/lib/node_modules/webpack/bin/webpack.js:335:15)
    at yargs.parse (/usr/local/lib/node_modules/webpack/bin/webpack.js:396:2)
    at Object.Yargs.self.parse (/usr/local/lib/node_modules/webpack/node_modules/yargs/yargs.js:533:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/webpack/bin/webpack.js:152:7)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
```

**Comment by pi0** [comment]
Thank you for the report. Should be fixed with release `1.1.4`.
