### ISSUE TITLE
Log failure when used with Karma

### ISSUE THREAD

**Issue by mohsinulhaq** [nuxt/webpackbar#38]
```
ERROR [karma]: TypeError: this.__write is not a function
    at WriteStream.write (node_modules/webpackbar/dist/utils/log-update.js:89:16)
    at adapters.forEach (node_modules/karma/lib/reporters/base.js:73:16)
    at Array.forEach (<anonymous>)
    at MochaReporter.BaseReporter.write (node_modules/karma/lib/reporters/base.js:68:19)
    at MochaReporter.BaseReporter.writeCommonMsg (node_modules/karma/lib/reporters/base.js:79:16)
    at MochaReporter.BaseReporter.onBrowserLog (node_modules/karma/lib/reporters/base.js:100:12)
    at Server.<anonymous> (node_modules/karma/lib/events.js:40:26)
    at Server.emit (events.js:187:15)
    at Browser.onInfo (node_modules/karma/lib/browser.js:100:20)
    at Socket.socket.on (node_modules/karma/lib/browser.js:272:38)
```

It seems that the your reporter is clashing with Karma's reporter when overriding `process.stdout.write`. Am I doing something wrong or is this a known issue?

**Comment by apepper** [comment]
I do have the same issue with version `3.1.4`. If I downgrade `webpackbar` to version `3.0.x` (e.g. `3.0.5`) the problem vanishes.

It looks like, that https://github.com/nuxt/webpackbar/commit/d51c508ba5a268bd65561076ade9da4ad16b122f introduces the bug.

**Comment by mohsinulhaq** [comment]
hi thanks for the info. Is there any significant feature difference between 3.1.x and 3.0.x? Right now, I have removed the plugin from karma config, but I can downgrade as well.

**Comment by apepper** [comment]
> Is there any significant feature difference between 3.1.x and 3.0.x?

According to https://github.com/nuxt/webpackbar/blob/master/CHANGELOG.md there are some bugfixes and one or two feature improvements.

**Comment by mohsinulhaq** [comment]
I saw that, but I was just asking you if you if there are any noticeable differences. I use it just for the progress bar.

**Comment by mohsinulhaq** [comment]
https://github.com/nuxt/webpackbar/issues/12

**Comment by apepper** [comment]
A college of my identified this: https://github.com/nuxt/webpackbar/commit/d51c508ba5a268bd65561076ade9da4ad16b122f#r31893923

**Comment by apepper** [comment]
@pi0 : A college of mine also identified a possible patch to fix the problem. See https://github.com/nuxt/webpackbar/commit/d51c508ba5a268bd65561076ade9da4ad16b122f#r31895162 for more details.

**Comment by mohsinulhaq** [comment]
awesome!
